export const MEMO = {
  ADD: 'ADD_MEMO',
  DELETE: 'DELETE_MEMO',
  OPEN_DETAIL: 'OPEM_DETAIL',
  CLOSE_DETAIL: 'CLOSE_DETAIL',
  OPEN_CHARACTER: 'OPEN_CHARACTER',
  CLOSE_CHARACTER: 'CLOSE_CHARACTER',
}