export const MEMO = {
  ADD: 'ADD_MEMO',
  DELETE: 'DELETE_MEMO',
  OPEN_DETAIL: 'OPEN_DETAIL',
  CLOSE_DETAIL: 'CLOSE_DETAIL',
  OPEN_CHARACTER: 'OPEN_CHARACTER',
  CLOSE_CHARACTER: 'CLOSE_CHARACTER',
  SET_CHARACTER: 'SET_CHARACTER',
  SET_SELECTED_MEMO: 'SET_SELECTED_MEMO',
}